CREATE OR REPLACE MODEL `project_name.dataset_name.model_name`
OPTIONS
(
model_type='logistic_reg',
labels = ['DIASCOT_180']
)
AS

#standardSQL
SELECT
  FECHA_INICIO_NOLAB, NUM_NOLAB, DUR_TRAMO_NOLAB, FECHA_FIN_NOLAB, HORAS_EMPR,DUR_EMPR,ALTA_AUTONOMO,NUM_AYUDA_EMPR,HORAS_COT_LAB_BONIF,DIAS_COT_LAB_BONIF,DUR_LAB_BONIF, HORAS_FORM,
  NUM_ACT_FORM,DUR_FORM,HORAS_ORI,DUR_ORI,NUM_ACT_ORI, DUR_NO_LAB, COD_PRIM_ACT, DIASCOT_180
FROM
    `sepe-ml.supertramos_v0.supertramos_v0`
WHERE 
    FECHA_FIN_NOLAB < '2018-12-31' AND NUM_NOLAB <> 0
;
